name: extended_image
description: Custom image widget for Boorusama.
publish_to: 'none' 

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

resolution: workspace

dependencies:
  cache_manager:
    path: ../cache_manager
  dio: ^5.7.0
  equatable: ^2.0.7
  extended_image_library:
    git:
      url: https://github.com/khoadng/extended_image_library.git
      ref: fork
  flutter:
    sdk: flutter
  flutter_avif:
    git:
      url: https://github.com/khoadng/flutter_avif.git
      ref: e144e7e6eb61af6e349be60a6a3afb21b4cdb613
      path: flutter_avif
  path: ^1.8.3
  path_provider: ^2.1.2
  retriable:
    path: ../retriable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
