
name: codegen
description: A personal lightweight code generation tool with template support
version: 1.0.0

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  mustache_template: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
