name: cache_manager
description: A generic cache manager for Boorusama
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  path: ^1.8.3
  path_provider: ^2.1.2
  extended_image_library:
    git:
      url: https://github.com/khoadng/extended_image_library.git
      ref: fork
  crypto: ^3.0.6
  background_downloader: ^9.1.1
  dio: ^5.4.0

dev_dependencies:
  lints: ^6.0.0
